modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Ephys/minecraft-magic-feather/issues"

[[mods]]
modId="magicfeather"
version="${file.jarVersion}"
displayName="Magic Feather"
updateJSONURL="https://mc-curse-update-checker.herokuapp.com/284745"
displayURL="https://www.curseforge.com/minecraft/mc-mods/magic-feather"
logoFile="logo.png"
credits="RWTema for the original angel ring"
authors="Ephys, EizhFox"
description='''
Magic Feather is an alternative take on the Angel Ring item from Extra Utilities.

It balances creative flight by making it only available around Beacons, thus forcing the player
to use alternative methods of travel when exploring.
'''
[[dependencies.magicfeather]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.magicfeather]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.magicfeather]]
    modId="cookiecore"
    mandatory=true
    versionRange="[1.18.2-4.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.magicfeather]]
    modId="alexsmobs"
    mandatory=false
    ordering="AFTER"
    versionRange="[1.0.0,)"

[[dependencies.magicfeather]]
    modId="curios"
    mandatory=false
    versionRange="[1.18.2-5.0.7.1,)"
    ordering="AFTER"
    side="BOTH"
